# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

# -- Project information -----------------------------------------------------

project = 'Knowledge'
html_title = 'Knowledge'
# html_title = 'Python LDC Training'
# project = 'Python & Git for SIEE -- 2022'
# copyright = '2021, Luis'
author = 'North Pikmin members'

# The short X.Y version
# version = '21-04-05'

# The full version, including alpha/beta/rc tags
# release = '21-04-05'
root_doc = 'index'  # needed for latexpdf default is index
                    # ci/cd will convert it to ldc_index

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.graphviz',
    'sphinx.ext.inheritance_diagram',
    'sphinx.ext.viewcode',
    'sphinx_git',
    'sphinx_inline_tabs',
    'sphinxcontrib.mermaid',
    'sphinx_copybutton',
    'sphinx_design',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', 'src/wip',
                    '*/README.rst', 'README.rst', 'archive']

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'pydata_sphinx_theme'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# -- Options for LaTeX output --------------------------------
# title = "Python trainning for LDC \\newline\\newline\\large Some subtitle possible here"
title = "Knowledge"

# latex_theme = 'manual'  # 'manual' to make a book, 'howto' to make an article
# latex_documents = [('ldc_index', 'mazars_ldc_python.tex', title, author, 'howto')]
latex_documents = [('index', 'mazars_ldc_python.tex', title, author, 'howto')]
latex_engine = 'xelatex'
latex_logo = './_static/logo_mazars.png'

latex_elements = {
  'papersize': 'a4paper',  # 'letterpaper' or 'a4paper'
  'pointsize': '10pt',     # global fontsize, possible values are 10pt, 11pt and 12pt
  'sphinxsetup': 'hmargin={1.5cm,1.5cm}, vmargin={2cm,2cm}',
  # 'classoptions': ',twocolumn',    # to have two columns
  # 'tableofcontents': '',           # To remove the TOC
  # 'babel' : '\\usepackage[english]{babel}',
  'preamble': r"""
     \usepackage{etoc}
  """,
     # \setcounter{tocdepth}{5}  # in preamble
  }
# etoc allow to have minitoc on each latex chapter with:
# .. raw: ... \etocsettocstyle{}{}\localtableofcontents
